const API = "/api";
const LINK_BAR = "/link-bar";
const NAV_BAR = "/nav-bar";
const HERO_SECTION = "/hero-section";
const WHY_CHOOSE_US = "/why-choose-us";
const FAQ = "/faq";
const PARTNERS = "/partners";
const OUR_SERVICES = "/our-services";
const WORK_FLOW = "/work-flow";

export const GET_ALL_LINK_BAR_DATA = `${API}${LINK_BAR}`;
export const GET_ALL_NAV_BAR_DATA = `${API}${NAV_BAR}`;
export const GET_ALL_HERO_SECTION_DATA = `${API}${HERO_SECTION}`;
export const GET_ALL_WHY_CHOOSE_US_DATA = `${API}${WHY_CHOOSE_US}`;
export const GET_ALL_FAQ_DATA = `${API}${FAQ}`;
export const UPDATE_FAQ_VIEW_COUNT = `${API}${FAQ}/update-view-count`;
export const GET_ALL_PARTNERS = `${API}${PARTNERS}`;
export const GET_ALL_OUR_SERVICES = `${API}${OUR_SERVICES}`;
export const GET_ACTIVE_WORK_FLOW_STEPS = `${API}${WORK_FLOW}`;
