export const USER_PROFILE_VIEW_PRIVILEGE = "DESTINATION"
export const USER_PROFILE_REVIEWS_VIEW_PRIVILEGE = "DESTINATION"
export const USER_PROFILE_PACKAGE_REVIEWS_VIEW_PRIVILEGE = "DESTINATION"
export const USER_PROFILE_TOUR_REVIEWS_VIEW_PRIVILEGE = "DESTINATION"
export const USER_PROFILE_TOUR_ACTIVITY_VIEW_PRIVILEGE = "DESTINATION"
export const USER_PROFILE_TOUR_DESTINATION_VIEW_PRIVILEGE = "DESTINATION"
export const USER_PROFILE_COUPONS_VIEW_PRIVILEGE = "DESTINATION"
export const USER_PROFILE_WALLET_VIEW_PRIVILEGE = "DESTINATION"
export const USER_PROFILE_BROWSER_HISTORY_VIEW_PRIVILEGE = "DESTINATION"
export const USER_PROFILE_ACCOUNT_SECURITY_VIEW_PRIVILEGE = "DESTINATION"
export const USER_PROFILE_NOTIFICATION_VIEW_PRIVILEGE = "DESTINATION"
export const USER_PROFILE_WISH_LIST_VIEW_PRIVILEGE = "DESTINATION"
export const USER_PROFILE_TOURS_VIEW_PRIVILEGE = "DESTINATION"
export const USER_PROFILE_COMPLETED_TOURS_VIEW_PRIVILEGE = "DESTINATION"
export const USER_PROFILE_UPCOMING_TOURS_VIEW_PRIVILEGE = "DESTINATION"
export const USER_PROFILE_USER_BENEFITS_VIEW_PRIVILEGE = "DESTINATION"
export const USER_PROFILE_REQUESTED_TOURS_VIEW_PRIVILEGE = "DESTINATION"
export const USER_PROFILE_CANCELLED_TOURS_VIEW_PRIVILEGE = "DESTINATION"
export const USER_PROFILE_PENDING_TOURS_VIEW_PRIVILEGE = "DESTINATION";

// Blogs
export const BLOG_CREATE_PRIVILEGE = "BLOG_CREATE";


// Pages View
export const HOME_PAGE_VIEW_PRIVILEGE = "HOME_PAGE_VIEW"